### ISSUE TITLE
Future problem function pretty_number().

### ISSUE THREAD

**Issue by yamilrh** [steemnova/steemnova#219]
Message: Undefined offset: 12
File: /includes/GeneralFunctions.php
Line: 423
URL: https://localhost/htdocs/game.php
PHP-Version: 7.3.6
PHP-API: apache2handler
2Moons Version: 2.4.git
Debug Backtrace:
#0 /includes/GeneralFunctions.php(423): errorHandler(8, 'Undefined offse...', 'C://xampp//htdocs...', 423, Array)
#1 /includes/pages/game/AbstractGamePage.class.php(278): shortly_number(5.2831195950595)
#2 /includes/pages/game/AbstractGamePage.class.php(301): AbstractGamePage->getNavigationData()
#3 /includes/pages/game/AbstractGamePage.class.php(407): AbstractGamePage->getPageData()
#4 /includes/pages/game/ShowOverviewPage.class.php(374): AbstractGamePage->display('page.overview.d...')
#5 /game.php(57): ShowOverviewPage->show()
#6 {main} 

GeneralFunctions.php
Line 403-424
`function shortly_number($number, $decial = NULL)
{
	$negate	= $number < 0 ? -1 : 1;
	$number	= abs($number);
    $unit	= array("", "K", "M", "B", "T", "Q", "Q+", "S", "S+", "O", "N");
	$key	= 0;
	
	if($number >= 1000000) {
		++$key;
		while($number >= 1000000)
		{
			++$key;
			$number = $number / 1000000;
		}
	} elseif($number >= 1000) {
		++$key;
		$number = $number / 1000;
	}
	
	$decial	= !is_numeric($decial) ? ((int) (((int)$number != $number) && $key != 0 && $number != 0 && $number < 100)) : $decial;
	return pretty_number($negate * $number, $decial).'&nbsp;'.$unit[$key];
}`

**Comment by yamilrh** [comment]
sip, realmente eso lo force a que diera ese error, y da cuando tus puntos totales sobrepasa ese valor N,  en este caso 12

**Comment by Qwatayean** [comment]
@yamilrh  because this is a milestone quite impossible to achieve (under normal conditions in a normal server. And truth be told, barely any player know what "N" means on these conditions.

A proposal could be, when number starts to be unreadable, have something like `"inf".$key - 10;` so in the case of 12, player would read "inf 2"

**Comment by yamilrh** [comment]
Si pero el caso, es que nada mas lo hice con esa tecnología o sea que a lo mejor es mas probable de que se muera antes, sin necesidad de llegar a N, ya que estructuras, flotas, defensas, y tecnologías suman . Graciaspuntos
