### ISSUE TITLE
Unable to complete installation

### ISSUE THREAD

**Issue by alfieo** [steemnova/steemnova#235]
Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system = '1' AND planet = '2' AND planet_type = '1'' at line 5

Query-Code:SELECT COUNT(*) as record FROM uni1_planets WHERE universe = 1 AND galaxy = 1 AND system = 1 AND planet = 2 AND planet_type = 1;
File: /includes/classes/Database.class.php
Line: 126
URL: http://2moons.uxgamezone.com/install/index.php?mode=install&step=8
PHP-Version: 7.4.32
PHP-API: fpm-fcgi
2Moons Version: 1.8.git (FILE)
Debug Backtrace:
#0 /includes/classes/Database.class.php(202): Database->_query()
#1 /includes/classes/PlayerUtil.class.php(42): Database->selectSingle()
#2 /includes/classes/PlayerUtil.class.php(88): PlayerUtil::isPositionFree()
#3 /install/index.php(580): PlayerUtil::createPlayer()
#4 {main}

**Comment by alfieo** [comment]
I am stuck on step 8 admin account creation.

**Comment by KidProtect** [comment]
This might be a problem with your database version. Make sure you install SteemNova on the latest version of database MySQL server or MariaDB server. Normally you should not get that error on a fresh install.

**Comment by alfieo** [comment]
My database server is MYSQL8 running on Ubuntu 22.04 so I won't believe it's with the database version. I think it's code itself not compatible with current version of MYSQL.

**Comment by JoseJorgeGC** [comment]
Que version mas actualizada de PHP se puede usar para correr el server?
